name: weather
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Dependency Injection
  get_it: ^7.2.0
  injectable: ^2.1.0

  # Network and Json
  json_annotation: ^4.7.0
  dio: ^4.0.6
  retrofit: ^3.3.1

  # Utility & Helpers
  cupertino_icons: ^1.0.5
  easy_localization: ^3.0.1
  equatable: ^2.0.5
  freezed_annotation: ^2.2.0
  l: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  injectable_generator: ^2.1.3
  retrofit_generator: ^4.2.0

flutter:
  uses-material-design: true

  assets:
    - resources/langs/
